### ISSUE TITLE
ARMhf/ARM64 build issue with GCC 6.2.0

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/fbalpha#98]
ARMhf/ARM64 build issue with GCC 6.2.0, with 0.2.97.39:

```
g++ -g -fdebug-prefix-map=/<<BUILDDIR>>/libretro-fba-0.2.97.38+r114+n55+co38+ct52~17~ubuntu16.10.1=. -fstack-protector-strong -Wformat -O2 -DNDEBUG -fPIC -Wno-write-strings -DUSE_SPEEDHACKS -D__LIBRETRO__ -D__LIBRETRO_OPTIMIZATIONS__ -DWANT_NEOGEOCD -DLSB_FIRST -marm -mfloat-abi=hard -DINLINE="static inline" -DSH2_INLINE="static inline" -D__LIBRETRO_OPTIMIZATIONS__   -DFRONTEND_SUPPORTS_RGB565 -Isrc/burner/win32 -Isrc/burner/libretro -Isrc/burner/libretro/tchar -Isrc/burn -Isrc/cpu -Isrc/burn/snd -Isrc/burn/devices -Isrc/intf -Isrc/intf/input -Isrc/intf/cd -Isrc/intf/audio -Isrc/burner -Isrc/cpu -Isrc/cpu/i8039 -Isrc/cpu/i8051 -Isrc/dep/libs/zlib -Isrc/burn/drv/capcom -Isrc/burn/drv/konami -Isrc/burn/drv/dataeast -Isrc/burn/drv/cave -Isrc/burn/drv/neogeo -Isrc/burn/drv/psikyo -Isrc/burn/drv/sega -Isrc/burn/drv/toaplan -Isrc/burn/drv/taito -Isrc/dep/generated -Isrc/dep/libs -c src/burn/drv/pre90s/d_cclimber.cpp -o src/burn/drv/pre90s/d_cclimber.o
src/burn/drv/pre90s/d_cclimber.cpp: In function ‘void cclimber_decrypt()’:
src/burn/drv/pre90s/d_cclimber.cpp:1518:2: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
  };
  ^
src/burn/drv/pre90s/d_cclimber.cpp:1518:2: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
src/burn/drv/pre90s/d_cclimber.cpp:1518:2: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
src/burn/drv/pre90s/d_cclimber.cpp:1518:2: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
src/burn/drv/pre90s/d_cclimber.cpp:1518:2: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
src/burn/drv/pre90s/d_cclimber.cpp:1518:2: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
src/burn/drv/pre90s/d_cclimber.cpp:1518:2: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
src/burn/drv/pre90s/d_cclimber.cpp:1518:2: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
src/burn/drv/pre90s/d_cclimber.cpp:1518:2: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
src/burn/drv/pre90s/d_cclimber.cpp:1518:2: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
makefile.libretro:613: recipe for target 'src/burn/drv/pre90s/d_cclimber.o' failed
make[2]: *** [src/burn/drv/pre90s/d_cclimber.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by barbudreadmon** [comment]
0.2.97.38 worked with gcc-6.1.1 ?

**Comment by sergiobenrocha2** [comment]
I don't know, first time I tried to build it on ubuntu 16.10

**Comment by barbudreadmon** [comment]
Ok.
Just to warn you, i don't consider building with compiler unsupported upstream as a bug.
You'll have to build with a gcc lesser than 6.0 or debug this yourself, i won't fix it, and i'm not even sure i'll merge fixes for this if there are too much changes (because it will make my work harder on the next fba release).
